### ISSUE TITLE
rhn_register upload certificate fail

### ISSUE THREAD

**Issue by KrE80r** [projectatomic/adb-vagrant-registration#114]
Looks like issue #60 resurfaced in version 1.3.0 

```
/home/krkr/.vagrant.d/gems/gems/vagrant-registration-1.3.0/plugins/guests/redhat/cap/rhn_register.rb:84:in `rhn_register_upload_certificate': undefined local variable or method `tmp' for VagrantPlugins::GuestRedHat::Cap::RhnRegister:Class (NameError)
Did you mean?  tap
	from /home/krkr/.vagrant.d/gems/gems/vagrant-registration-1.3.0/plugins/guests/redhat/cap/rhn_register.rb:20:in `rhn_register_register'
	from /usr/share/vagrant/lib/vagrant/capability_host.rb:111:in `call'
	from /usr/share/vagrant/lib/vagrant/capability_host.rb:111:in `capability'
	from /usr/share/vagrant/lib/vagrant/guest.rb:43:in `capability'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-registration-1.3.0/plugins/guests/redhat/cap/registration.rb:27:in `registration_register'
	from /usr/share/vagrant/lib/vagrant/capability_host.rb:111:in `call'
	from /usr/share/vagrant/lib/vagrant/capability_host.rb:111:in `capability'
	from /usr/share/vagrant/lib/vagrant/guest.rb:43:in `capability'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-registration-1.3.0/lib/vagrant-registration/action/register.rb:27:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/wait_till_up.rb:78:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/start_domain.rb:294:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/set_boot_order.rb:60:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_network_interfaces.rb:143:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_networks.rb:80:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/share_folders.rb:20:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:18:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_domain.rb:244:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/handle_box_image.rb:111:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /home/krkr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/machine.rb:224:in `action_raw'
	from /usr/share/vagrant/lib/vagrant/machine.rb:199:in `block in action'
	from /usr/share/vagrant/lib/vagrant/environment.rb:561:in `lock'
	from /usr/share/vagrant/lib/vagrant/machine.rb:185:in `call'
	from /usr/share/vagrant/lib/vagrant/machine.rb:185:in `action'
	from /usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

**Comment by KrE80r** [comment]
I tried editing line 84 in rhn_register.rb

Changing :
`cert_file_content = File.read(machine.config.registration.ca_cert, tmp) `
To
`cert_file_content = File.read(machine.config.registration.ca_cert)`

And it did work afterwards
